### PR TITLE
Major changes to project setup

### PR DESCRIPTION
**Pull request by Samcfuchs**
I organized the project, moving everything into folders in /assets/ and /js/

I also added a link to the options page from the new tab page (and it spins!). I think it's pretty subtle, but I can tone it down more if we need that.

I also added a link to the source code from the options page.

### CODE REVIEW

**Comment by ErikBoesen** [comment]
Not sure if the `assets` folder is the best method of organization.

**Comment by Samcfuchs** [comment]
What would you suggest as an alternative?

**Comment by ErikBoesen** [comment]
Moving it back to how it was before.

**Comment by Samcfuchs** [comment]
It was kind of a mess before, though. Maybe we could move the sub folders of `assets` to be subfolders of the parent directory?

**Comment by ErikBoesen** [comment]
That's what I meant.

**Comment by Samcfuchs** [comment]
Ok, I can do that if you like, but that's not a big task. In the future, it'd be easier if you let me know before merging, so I could fix it in my fork.

**Comment by ErikBoesen** [comment]
Okay, sorry. Will do next time. I just wanted to merge all the other features you changed/added.

**Comment by Samcfuchs** [comment]
No problem, remember that any commits I make on my fork are automatically added to the PR, so it's not any trouble to ask for small changes. 👍

**Comment by ErikBoesen** [comment]
Yeah, I know that, just forgot for some reason

**Comment by Samcfuchs** [comment]
No problem!

**Pull request merged**
