### PR TITLE
A couple minor fixes and WHITESPACE!!!

### PR DESCRIPTION
**Pull request by Samcfuchs**

### CODE REVIEW

**Comment by ErikBoesen** [comment]
What exactly did you do to the whitespace? I can't tell.

**Comment by Samcfuchs** [comment]
I fixed indentation and removed trailing whitespace.

**Comment by ErikBoesen** [comment]
How did you fix indentation? And I don't know why there would be whitespace, as Atom automatically removes it. Odd.

**Comment by Samcfuchs** [comment]
Vim is a magical thing
> mixed-indentation

`:retab`

fixed.
> trailing whitespace

`:%s/\s\+$`

fixed. Atom looking so great now?

**Comment by ErikBoesen** [comment]
u r meen

**Comment by Samcfuchs** [comment]
Oh well, not my fault you're unworthy of a good editor.

**Comment by ErikBoesen** [comment]
[1-800-SO-RUDE](tel:1-800-SO-RUDE)

**Pull request merged**
